### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by mascai** [GameAnalytics/GA-SDK-CPP#124]
I am trying to install SDK on Windows10
My actions

```
git clone https://github.com/GameAnalytics/GA-SDK-CPP
# open Developer Comand Prompt for VS2022
python build\jenkins\main.py 
```

I have an error:
```
(venv) C:\dev\GA-SDK-CPP>python build\jenkins\main.py
-------------- TIZEN ---------------
--> DOWNLOADING TIZEN
Traceback (most recent call last):
  File "C:\dev\GA-SDK-CPP\build\jenkins\main.py", line 115, in <module>
    main(sys.argv[1:])
  File "C:\dev\GA-SDK-CPP\build\jenkins\main.py", line 104, in main
    install_dependencies(installTizen=installTizen, silent=silent)
  File "C:\dev\GA-SDK-CPP\build\jenkins\install_dependencies.py", line 270, in install_dependencies
    install_tizen(silent=silent)
  File "C:\dev\GA-SDK-CPP\build\jenkins\install_dependencies.py", line 149, in install_tizen
    download(TIZEN_URL, tizen_package, silent=silent)
  File "C:\dev\GA-SDK-CPP\build\jenkins\install_dependencies.py", line 65, in download
    urllib.request.urlretrieve(url, destination, reporthook)
  File "C:\Users\vboxuser\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\vboxuser\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vboxuser\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vboxuser\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\vboxuser\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vboxuser\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\vboxuser\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

My internat connection is fine
Python:
```
(venv) C:\dev\GA-SDK-CPP>python --version
Python 3.11.8
```

**Comment by mascai** [comment]
Looks like URL
https://download.tizen.org/sdk/Installer/tizen-sdk-2.4-rev8/tizen-web-cli_TizenSDK_2.4.0_Rev8_windows-64.exe
isn't working
